### ISSUE TITLE
Remote connect, tramp and repository jars

### ISSUE THREAD

**Issue by darkleaf** [clojure-emacs/cider#2091]
I have:
+ docker for mac
+ nREPL server launched in docker container
+ the host and  the container share app folder
+ cider correctly connected to that repl server
+ tramp not used
+ it's work fine, it's eval code in buffers

I open doc(C-c C-d C-d) and I see `clojure.spec.alpha/def is defined in jar:file:/root/.m2/repository/org/clojure/spec.alpha/0.1.123/spec.alpha-0.1.123.jar!/clojure/spec/alpha.clj.`
`/root/.m2/` are placed in docker volume. Host don't have access to them.
So I can't view this file in emacs.

When I open a project file via tramp than I can view this jar in emacs.

I want:
+ launch repl server in docker
+ connect cider to it
+ open project files without tramp
+ open jars from local repo with tramp

I don't understand this workflow completely.
Google don't gave me some examples.
May be I wont something unrealistic.

**Comment by darkleaf** [comment]
```
version: '3'

services:
  app:
    image: clojure:lein-2.7.1-alpine
    working_dir: "${PWD}"
    command: lein repl :headless :host "0.0.0.0" :port 4100
    ports:
      - "4100:4100" # repl
      - "4101:4101" # http
    volumes:
      - ".:${PWD}"
      - ~/.lein:/root/.lein:ro
```

Add `:local-repo "local-m2"` into project.clj
